database:
  host: "127.0.0.1"
  port: 3306
  config: ""
  user: "root"
  password: ""
  dbname: "seckill"
  charset: "utf8mb4"
redis:
  host: "127.0.0.1"
  port: 6379
  user: "root"
  passwd: ""
  dbname: 0
rabbitmq:
  host: "127.0.0.1"
  port: 5672
  user: "guest"
  passwd: "guest"
  vhost: ""
