database:
  host: "192.168.128.128"
  port: 3307
  config: ""
  user: "root"
  password: ""
  dbname: "seckill"
  charset: "utf8mb4"
redis:
  host: "localhost"
  port: 6379
  user: "root"
  passwd: ""
  dbname: 0