// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuotum = "quota"

// Quotum 限额表
type Quotum struct {
	ID         uint32    `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`                            // ID
	GoodsID    *uint32   `gorm:"column:goods_id;type:bigint;comment:商品ID" json:"goods_id"`                                            // 商品ID
	Num        uint32    `gorm:"column:num;type:int;not null;comment:限额" json:"num"`                                                  // 限额
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	ModifyTime time.Time `gorm:"column:modify_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"modify_time"` // 修改时间
}

// TableName Quotum's table name
func (*Quotum) TableName() string {
	return TableNameQuotum
}
