// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User 用户表
type User struct {
	ID           uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                  // 用户ID
	Username     string    `gorm:"column:username;type:varchar(50);not null;comment:用户名" json:"username"`                             // 用户名
	Email        string    `gorm:"column:email;type:varchar(100);not null;comment:电子邮件" json:"email"`                                 // 电子邮件
	PasswordHash string    `gorm:"column:password_hash;type:varchar(255);not null;comment:密码哈希" json:"password_hash"`                 // 密码哈希
	FirstName    *string   `gorm:"column:first_name;type:varchar(50);comment:名" json:"first_name"`                                    // 名
	LastName     *string   `gorm:"column:last_name;type:varchar(50);comment:姓" json:"last_name"`                                      // 姓
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
