// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.1
// source: api/my_sec_kill/v1/my_sec_kill.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMySecKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMySecKillRequest) Reset() {
	*x = CreateMySecKillRequest{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMySecKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMySecKillRequest) ProtoMessage() {}

func (x *CreateMySecKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMySecKillRequest.ProtoReflect.Descriptor instead.
func (*CreateMySecKillRequest) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{0}
}

type CreateMySecKillReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMySecKillReply) Reset() {
	*x = CreateMySecKillReply{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMySecKillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMySecKillReply) ProtoMessage() {}

func (x *CreateMySecKillReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMySecKillReply.ProtoReflect.Descriptor instead.
func (*CreateMySecKillReply) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{1}
}

type UpdateMySecKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMySecKillRequest) Reset() {
	*x = UpdateMySecKillRequest{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMySecKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMySecKillRequest) ProtoMessage() {}

func (x *UpdateMySecKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMySecKillRequest.ProtoReflect.Descriptor instead.
func (*UpdateMySecKillRequest) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{2}
}

type UpdateMySecKillReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMySecKillReply) Reset() {
	*x = UpdateMySecKillReply{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMySecKillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMySecKillReply) ProtoMessage() {}

func (x *UpdateMySecKillReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMySecKillReply.ProtoReflect.Descriptor instead.
func (*UpdateMySecKillReply) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{3}
}

type DeleteMySecKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMySecKillRequest) Reset() {
	*x = DeleteMySecKillRequest{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMySecKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMySecKillRequest) ProtoMessage() {}

func (x *DeleteMySecKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMySecKillRequest.ProtoReflect.Descriptor instead.
func (*DeleteMySecKillRequest) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{4}
}

type DeleteMySecKillReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMySecKillReply) Reset() {
	*x = DeleteMySecKillReply{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMySecKillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMySecKillReply) ProtoMessage() {}

func (x *DeleteMySecKillReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMySecKillReply.ProtoReflect.Descriptor instead.
func (*DeleteMySecKillReply) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{5}
}

type GetMySecKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySecKillRequest) Reset() {
	*x = GetMySecKillRequest{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySecKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySecKillRequest) ProtoMessage() {}

func (x *GetMySecKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySecKillRequest.ProtoReflect.Descriptor instead.
func (*GetMySecKillRequest) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{6}
}

type GetMySecKillReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySecKillReply) Reset() {
	*x = GetMySecKillReply{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySecKillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySecKillReply) ProtoMessage() {}

func (x *GetMySecKillReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySecKillReply.ProtoReflect.Descriptor instead.
func (*GetMySecKillReply) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{7}
}

type ListMySecKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMySecKillRequest) Reset() {
	*x = ListMySecKillRequest{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySecKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySecKillRequest) ProtoMessage() {}

func (x *ListMySecKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySecKillRequest.ProtoReflect.Descriptor instead.
func (*ListMySecKillRequest) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{8}
}

type ListMySecKillReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMySecKillReply) Reset() {
	*x = ListMySecKillReply{}
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySecKillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySecKillReply) ProtoMessage() {}

func (x *ListMySecKillReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySecKillReply.ProtoReflect.Descriptor instead.
func (*ListMySecKillReply) Descriptor() ([]byte, []int) {
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP(), []int{9}
}

var File_api_my_sec_kill_v1_my_sec_kill_proto protoreflect.FileDescriptor

var file_api_my_sec_kill_v1_my_sec_kill_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c,
	0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73,
	0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79,
	0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18,
	0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x79,
	0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x53, 0x65,
	0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x89, 0x04, 0x0a, 0x09, 0x4d,
	0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x67, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x2a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79,
	0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x67, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63,
	0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65,
	0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65,
	0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x67, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x2a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b,
	0x69, 0x6c, 0x6c, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63,
	0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x53, 0x65,
	0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x61, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x53, 0x65, 0x63,
	0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65,
	0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79,
	0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x53, 0x0a, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79,
	0x5f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x3b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x74, 0x73, 0x74,
	0x6f, 0x72, 0x6d, 0x68, 0x75, 0x62, 0x2f, 0x62, 0x69, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x58, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x63,
	0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescOnce sync.Once
	file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescData = file_api_my_sec_kill_v1_my_sec_kill_proto_rawDesc
)

func file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescGZIP() []byte {
	file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescOnce.Do(func() {
		file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescData)
	})
	return file_api_my_sec_kill_v1_my_sec_kill_proto_rawDescData
}

var file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_my_sec_kill_v1_my_sec_kill_proto_goTypes = []any{
	(*CreateMySecKillRequest)(nil), // 0: api.my_sec_kill.v1.CreateMySecKillRequest
	(*CreateMySecKillReply)(nil),   // 1: api.my_sec_kill.v1.CreateMySecKillReply
	(*UpdateMySecKillRequest)(nil), // 2: api.my_sec_kill.v1.UpdateMySecKillRequest
	(*UpdateMySecKillReply)(nil),   // 3: api.my_sec_kill.v1.UpdateMySecKillReply
	(*DeleteMySecKillRequest)(nil), // 4: api.my_sec_kill.v1.DeleteMySecKillRequest
	(*DeleteMySecKillReply)(nil),   // 5: api.my_sec_kill.v1.DeleteMySecKillReply
	(*GetMySecKillRequest)(nil),    // 6: api.my_sec_kill.v1.GetMySecKillRequest
	(*GetMySecKillReply)(nil),      // 7: api.my_sec_kill.v1.GetMySecKillReply
	(*ListMySecKillRequest)(nil),   // 8: api.my_sec_kill.v1.ListMySecKillRequest
	(*ListMySecKillReply)(nil),     // 9: api.my_sec_kill.v1.ListMySecKillReply
}
var file_api_my_sec_kill_v1_my_sec_kill_proto_depIdxs = []int32{
	0, // 0: api.my_sec_kill.v1.MySecKill.CreateMySecKill:input_type -> api.my_sec_kill.v1.CreateMySecKillRequest
	2, // 1: api.my_sec_kill.v1.MySecKill.UpdateMySecKill:input_type -> api.my_sec_kill.v1.UpdateMySecKillRequest
	4, // 2: api.my_sec_kill.v1.MySecKill.DeleteMySecKill:input_type -> api.my_sec_kill.v1.DeleteMySecKillRequest
	6, // 3: api.my_sec_kill.v1.MySecKill.GetMySecKill:input_type -> api.my_sec_kill.v1.GetMySecKillRequest
	8, // 4: api.my_sec_kill.v1.MySecKill.ListMySecKill:input_type -> api.my_sec_kill.v1.ListMySecKillRequest
	1, // 5: api.my_sec_kill.v1.MySecKill.CreateMySecKill:output_type -> api.my_sec_kill.v1.CreateMySecKillReply
	3, // 6: api.my_sec_kill.v1.MySecKill.UpdateMySecKill:output_type -> api.my_sec_kill.v1.UpdateMySecKillReply
	5, // 7: api.my_sec_kill.v1.MySecKill.DeleteMySecKill:output_type -> api.my_sec_kill.v1.DeleteMySecKillReply
	7, // 8: api.my_sec_kill.v1.MySecKill.GetMySecKill:output_type -> api.my_sec_kill.v1.GetMySecKillReply
	9, // 9: api.my_sec_kill.v1.MySecKill.ListMySecKill:output_type -> api.my_sec_kill.v1.ListMySecKillReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_my_sec_kill_v1_my_sec_kill_proto_init() }
func file_api_my_sec_kill_v1_my_sec_kill_proto_init() {
	if File_api_my_sec_kill_v1_my_sec_kill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_my_sec_kill_v1_my_sec_kill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_my_sec_kill_v1_my_sec_kill_proto_goTypes,
		DependencyIndexes: file_api_my_sec_kill_v1_my_sec_kill_proto_depIdxs,
		MessageInfos:      file_api_my_sec_kill_v1_my_sec_kill_proto_msgTypes,
	}.Build()
	File_api_my_sec_kill_v1_my_sec_kill_proto = out.File
	file_api_my_sec_kill_v1_my_sec_kill_proto_rawDesc = nil
	file_api_my_sec_kill_v1_my_sec_kill_proto_goTypes = nil
	file_api_my_sec_kill_v1_my_sec_kill_proto_depIdxs = nil
}
